### ISSUE TITLE
No Longer functional

### ISSUE THREAD

**Issue by ghost** [lumaaaaaa/ttDownloader#2]
Heyo! I really appreciate your work on the gorgon.go. However, i downloaded this today and it didn't receive any videos, testing a bit the http response code is 200, so i'm not sure what the problem is. A project like this probably takes a lot of upkeep, and you said last year in a different issue that you don't have much time. I would really appreciate you taking the time to look into this, thank you!

**Comment by ghost** [comment]
I am using this search functionality for my own personal project btw...so even if you can point me in the right direction as to how to fix it, that would be great, and if i do i'll create a pull request here too. Thank you.

P.S. Thank you  for the struct in response.go...would have been a pain in the ass without finding that

**Comment by lumaaaaaa** [comment]
Hey there, appreciate you reaching out and taking a look at my project. I have renewed interest in TikTok reverse engineering, so if having my tool back in working order is something you're still looking for, let me know! If so I can take a peek later this week and try and get things operational.

About the status 200 codes: this project uses reverse engineered private APIs from the TikTok mobile app, and as such can be really unstable when things change in that API spec. As part of Bytedance's security-through-obscurity practice, if a request is somehow malformed, it'll still just through a 200 with no body. Where I HAVE seen this before is when the signing algorithm changes. TikTok private APIs require (most) requests to be signed cryptographically, passing a signature that is calculated on-device in the headers (X-Gorgon, X-Argus, X-Ladon, X-Khronos). I haven't reversed the latest versions of these (nor do I intend to, it's simply not profitable for me to spend that much time on this) but I'm willing to be the server is looking for the latest version of these signature headers, breaking this program. I'll determine whether or not this is something I can solve in the next few days hopefully, potentially finding a bypass.

cute pfp btw

**Comment by ghost** [comment]
Thanks man! I would appreciate that a lot! Thanks for the in-depth response :)

**Comment by lumaaaaaa** [comment]
Hey @LordRusk,

I did a bit more reverse-engineering and found a hacky workaround. Things should be working again, although it appears that the API is enforcing that users can only fetch the first 30 videos. I don't intend on finding a way around that, I hope this is enough for your use case!

Let me know if things are working on your end and I can go ahead and close this issue.

Thanks!

**Comment by ghost** [comment]
Really appreciate it dude! I'm already brainstorming meta searching across accounts, so ip ranges shouldn't be hard...again, I really appreciate it!

**Comment by lumaaaaaa** [comment]
Of course. Let me know if there's anything else I can do.
